[[observability-spans]]
=== Observability - Spans

Below you can find a list of all spans declared by this project.

[[observability-spans-circuit-breaker-function-observation]]
==== Circuit Breaker Function Observation Span

> Observation created when we wrap a Function passed to the CircuitBreaker as fallback.

**Span name** `spring.cloud.circuitbreaker` (defined by convention class `org.springframework.cloud.client.circuitbreaker.observation.DefaultCircuitBreakerObservationConvention`).

Fully qualified name of the enclosing class `org.springframework.cloud.client.circuitbreaker.observation.CircuitBreakerObservationDocumentation`.

IMPORTANT: All tags must be prefixed with `spring.cloud.circuitbreaker` prefix!

.Tag Keys
|===
|Name | Description
|`spring.cloud.circuitbreaker.type` _(required)_|Defines the type of wrapped lambda.
|===



[[observability-spans-circuit-breaker-supplier-observation]]
==== Circuit Breaker Supplier Observation Span

> Observation created when we wrap a Supplier passed to the CircuitBreaker.

**Span name** `spring.cloud.circuitbreaker` (defined by convention class `org.springframework.cloud.client.circuitbreaker.observation.DefaultCircuitBreakerObservationConvention`).

Fully qualified name of the enclosing class `org.springframework.cloud.client.circuitbreaker.observation.CircuitBreakerObservationDocumentation`.

IMPORTANT: All tags must be prefixed with `spring.cloud.circuitbreaker` prefix!

.Tag Keys
|===
|Name | Description
|`spring.cloud.circuitbreaker.type` _(required)_|Defines the type of wrapped lambda.
|===




